import test from 'node:test';
import assert from 'node:assert/strict';
import { createBusinessMarketplaceService } from '../server-side/business-marketplace.mjs';
import { createBusinessHandler } from '../api/business.js';

const env={SUPABASE_URL:'https://market.test',SUPABASE_ANON_KEY:'sb_publishable_test',SUPABASE_SERVICE_ROLE_KEY:'service-test'};
const org='11111111-1111-4111-8111-111111111111'; const user='22222222-2222-4222-8222-222222222222';
function req(method='GET',url=`/api/business/organizations/${org}/card-market`,body){return {method,url,headers:{authorization:'Bearer verified'},params:{orgId:org,setId:'33333333-3333-4333-8333-333333333333'},...(body===undefined?{}:{body})};}
function response(){return {status:null,body:'',writeHead(s){this.status=s;},end(b){this.body=b||'';}};}
function fakeFetch(url,options={}){const path=new URL(url).pathname;if(path==='/auth/v1/user')return Promise.resolve(new Response(JSON.stringify({id:user,email:'member@test',email_confirmed_at:'2026-01-01'})));if(path.includes('/rpc/')){const name=path.split('/').at(-1);if(name==='org_card_market_context')return Promise.resolve(new Response(JSON.stringify({role:'owner',department:'Sales',entitlementActive:true,departments:['Sales']})));if(name==='org_card_market_list')return Promise.resolve(new Response(JSON.stringify([])));if(name==='org_card_market_save_v2')return Promise.resolve(new Response(JSON.stringify({id:'33333333-3333-4333-8333-333333333333',status:'draft'})));if(name==='org_card_market_detail')return Promise.resolve(new Response(JSON.stringify({id:'33333333-3333-4333-8333-333333333333',cards:[{text:'x'}]})));return Promise.resolve(new Response(JSON.stringify({})))}return Promise.resolve(new Response('{}'));}
test('card market service returns contract metadata and validates card shape',async()=>{const s=createBusinessMarketplaceService({env,fetchImpl:fakeFetch});const listed=await s.list(req());assert.equal(listed.entitlementActive,true);assert.equal(listed.department,'Sales');assert.ok(Array.isArray(listed.officialActivities));assert.equal(typeof listed.officialActivities[0].minParticipants,'number');const base={title:'あ'.repeat(100),description:'',audience:'group',minParticipants:2,maxParticipants:8,visibility:'all',status:'draft',cards:[{text:'カード'}]};assert.equal((await s.save(req('POST',`/api/business/organizations/${org}/card-market/sets`,base))).set.status,'draft');await assert.rejects(()=>s.save(req('POST',`/api/business/organizations/${org}/card-market/sets`,{...base,cards:[{text:'x',extra:true}]})),e=>e.code==='INVALID_REQUEST');await assert.rejects(()=>s.save(req('POST',`/api/business/organizations/${org}/card-market/sets`,{...base,title:'あ'.repeat(121)})),e=>e.code==='INVALID_REQUEST');});
test('card market routes connect detail and owner list',async()=>{const market=createBusinessMarketplaceService({env,fetchImpl:fakeFetch});const service={};const handler=createBusinessHandler({service,market,rate:async()=>{}});const detail=response();await handler(req('GET',`/api/business/organizations/${org}/card-market/sets/33333333-3333-4333-8333-333333333333`),detail);assert.equal(detail.status,200);const owner=response();await handler(req('GET',`/api/business/organizations/${org}/card-market/owner`),owner);assert.equal(owner.status,200);});
