import test from 'node:test';
import assert from 'node:assert/strict';
import { createBusinessService } from '../server-side/business.mjs';

const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_test',SUPABASE_SERVICE_ROLE_KEY:'service-role-test'};
const req=(body={},org='11111111-1111-4111-8111-111111111111')=>({headers:{authorization:'Bearer verified'},body,params:{orgId:org},url:'/api/business'});
function fakeFetch(url,options={}){const u=new URL(url);if(u.pathname==='/auth/v1/user')return Promise.resolve(new Response(JSON.stringify({id:'22222222-2222-4222-8222-222222222222',email:'employee@example.test',email_confirmed_at:'2026-01-01'}),{status:200}));if(u.pathname.includes('/rpc/')){const name=u.pathname.split('/').at(-1);const b=JSON.parse(options.body||'{}');if(name==='org_claim_members')return Promise.resolve(new Response('0',{status:200}));if(name==='org_workspace')return Promise.resolve(new Response(JSON.stringify({organization:{id:b.p_org,name:'Org',slug:'org'},role:'member',allowedThemeIds:['team','self-work','date','friends'],featureFlags:{group_play:true,solo_play:true,theme_mix:true,audio:true,theme_tags:true}}),{status:200}));if(name==='org_set_policy')return Promise.resolve(new Response(JSON.stringify({organization_id:b.p_org,allowed_theme_ids:b.p_themes,feature_flags:b.p_flags}),{status:200}));return Promise.resolve(new Response(JSON.stringify(true),{status:200}));}return Promise.resolve(new Response('{}',{status:200}));}
test('workspace metadata returns only policy themes for members',async()=>{const s=createBusinessService({env,fetchImpl:fakeFetch});const x=await s.metadata(req());assert.equal(x.themes[0].id,'team');assert.equal(x.catalog,undefined);});
test('session rejects extra participant data and invalid count',async()=>{const s=createBusinessService({env,fetchImpl:fakeFetch});await assert.rejects(()=>s.start(req({mode:'group',themeIds:['team'],participantCount:3,participants:['secret']})),e=>e.code==='INVALID_REQUEST');await assert.rejects(()=>s.start(req({mode:'group',themeIds:['team'],participantCount:1})),e=>e.code==='PARTICIPANT_COUNT_INVALID');});
test('policy rejects unknown flags',async()=>{const s=createBusinessService({env,fetchImpl:fakeFetch});await assert.rejects(()=>s.policy(req({allowedThemeIds:['team'],featureFlags:{group_play:true,solo_play:true,theme_mix:false,audio:true,theme_tags:true,secret:true}})),e=>e.code==='INVALID_REQUEST');});
test('valid group and solo sessions succeed while pair with three rejects',async()=>{const s=createBusinessService({env,fetchImpl:fakeFetch});const group=await s.start(req({mode:'group',themeIds:['team'],participantCount:3}));assert.equal(group.themes[0].id,'team');const solo=await s.start(req({mode:'solo',themeIds:['self-work'],participantCount:1}));assert.equal(solo.mode,'solo');await assert.rejects(()=>s.start(req({mode:'group',themeIds:['date'],participantCount:3})),e=>e.code==='PARTICIPANT_COUNT_INVALID');});
test('duplicate, disallowed and R18 themes are rejected',async()=>{const s=createBusinessService({env,fetchImpl:fakeFetch});await assert.rejects(()=>s.start(req({mode:'group',themeIds:['team','team'],participantCount:2})),e=>e.code==='INVALID_REQUEST');await assert.rejects(()=>s.start(req({mode:'group',themeIds:['couples'],participantCount:2})),e=>e.code==='THEME_NOT_ALLOWED');await assert.rejects(()=>s.policy(req({allowedThemeIds:['intimacy'],featureFlags:{group_play:true,solo_play:true,theme_mix:false,audio:true,theme_tags:true}})),e=>e.code==='INVALID_REQUEST');});
test('missing or unverified auth and migration errors are stable',async()=>{const noAuth={...req(),headers:{}};const s=createBusinessService({env,fetchImpl:fakeFetch});await assert.rejects(()=>s.metadata(noAuth),e=>e.code==='UNAUTHENTICATED');const bad=async(url,options)=>url.endsWith('/auth/v1/user')?new Response(JSON.stringify({id:'x',email:'x'}),{status:200}):fakeFetch(url,options);await assert.rejects(()=>createBusinessService({env,fetchImpl:bad}).metadata(req()),e=>e.code==='UNAUTHENTICATED');const missing=async(url,options)=>url.includes('/rpc/org_workspace')?new Response(JSON.stringify({code:'PGRST202'}),{status:404}):fakeFetch(url,options);await assert.rejects(()=>createBusinessService({env,fetchImpl:missing}).metadata(req()),e=>e.code==='BUSINESS_MIGRATION_UNAVAILABLE');});
test('CSV member limits and row validation are enforced before RPC',async()=>{const s=createBusinessService({env,fetchImpl:fakeFetch});const row={email:'a@example.test',display_name:'A',department:''};await s.importMembers(req(),Array.from({length:500},(_,i)=>({...row,email:`a${i}@example.test`})));await assert.rejects(()=>s.importMembers(req(),Array.from({length:501},(_,i)=>({...row,email:`b${i}@example.test` }))),e=>e.code==='CSV_LIMIT');await assert.rejects(()=>s.importMembers(req(),[row,row]),e=>e.code==='CSV_INVALID');});
test('CSV department may be omitted but explicit null is invalid',async()=>{const s=createBusinessService({env,fetchImpl:fakeFetch});await s.importMembers(req(),[{email:'omit@example.test',display_name:'Omit'}]);await assert.rejects(()=>s.importMembers(req(),[{email:'null@example.test',display_name:'Null',department:null}]),e=>e.code==='CSV_INVALID');});
test('service rate keys use user and operation scope',async()=>{const calls=[];const rate=async(key)=>{calls.push(key);return 0;};const s=createBusinessService({env,fetchImpl:fakeFetch,rateImpl:rate});await s.metadata(req());await s.start(req({mode:'group',themeIds:['team'],participantCount:2}));assert.deepEqual(calls,['business:user:read:22222222-2222-4222-8222-222222222222','business:user:mutation:22222222-2222-4222-8222-222222222222']);});
test('business activity and quiz starts fail closed on disabled policies',async()=>{
  const disabledFetch=async(url,options)=>{const response=await fakeFetch(url,options); if(url.includes('/rpc/org_workspace')) { const value=await response.json(); value.featureFlags.group_play=false; return new Response(JSON.stringify(value),{status:200}); } if(url.includes('/rpc/org_content_policy')) return new Response(JSON.stringify({businessActivities:true,customQuiz:false,generalQuiz:true}),{status:200}); return response;};
  const s=createBusinessService({env,fetchImpl:disabledFetch});
  const activityReq={...req({participantCount:2}),params:{orgId:'11111111-1111-4111-8111-111111111111',activityId:'meeting-checkin'}};
  await assert.rejects(()=>s.activityStart(activityReq),e=>e.code==='INVALID_REQUEST');
  const quizReq={...req(),params:{orgId:'11111111-1111-4111-8111-111111111111',quizId:'11111111-1111-4111-8111-111111111111'}};
  await assert.rejects(()=>s.quizStart(quizReq),e=>e.code==='FEATURE_DISABLED');
});
test('quiz field limits count Unicode characters while payload uses UTF-8 bytes',async()=>{
  const ownerFetch=async(url,options)=>{const response=await fakeFetch(url,options); if(url.includes('/rpc/org_workspace')) { const value=await response.json(); value.role='owner'; return new Response(JSON.stringify(value),{status:200}); } return response;};
  const s=createBusinessService({env,fetchImpl:ownerFetch});
  const base={description:'',status:'draft',questions:[{question:'問題',answer:'正解'}]};
  await s.createQuiz({...req({...base,title:'あ'.repeat(100)})});
  await assert.rejects(()=>s.createQuiz({...req({...base,title:'あ'.repeat(121)})}),e=>e.code==='INVALID_REQUEST');
});
