import { createHmac, timingSafeEqual } from 'node:crypto';
import { MAX_BODY_BYTES, isProduction } from './config.mjs';
export function json(res, status, body, extra = {}) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...extra }); res.end(JSON.stringify(body)); }
export function noStore(res) { res.setHeader?.('Cache-Control', 'no-store'); }
export async function body(req) { const contentType = String(req.headers?.['content-type'] || '').split(';')[0].trim().toLowerCase(); if (contentType && contentType !== 'application/json') throw Object.assign(new Error('content type'), { status: 415 }); if (req.body && typeof req.body === 'object') { if (Buffer.byteLength(JSON.stringify(req.body)) > MAX_BODY_BYTES) throw Object.assign(new Error('body too large'), { status: 413 }); return req.body; } let size = 0; const chunks = []; for await (const chunk of req) { size += chunk.length; if (size > MAX_BODY_BYTES) throw Object.assign(new Error('body too large'), { status: 413 }); chunks.push(chunk); } if (!size) return {}; try { const parsed = JSON.parse(Buffer.concat(chunks).toString('utf8')); if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error(); return parsed; } catch { throw Object.assign(new Error('invalid json'), { status: 400 }); } }
export function exactKeys(value, keys) { return Object.keys(value).every((key) => keys.includes(key)) && keys.every((key) => Object.prototype.hasOwnProperty.call(value, key)); }
export function sameOrigin(req) { const origin = req.headers?.origin; if (!origin) return true; try { return new URL(origin).host === (req.headers.host || new URL(process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost').host); } catch { return false; } }
export function cookie(req, name) { const raw = req.headers?.cookie || ''; const match = raw.split(';').map((v) => v.trim()).find((v) => v.startsWith(`${name}=`)); if (!match) return ''; try { return decodeURIComponent(match.slice(name.length + 1)); } catch { return ''; } }
export function setCookie(res, value, maxAge) { const attrs = [`mingle_admin=${encodeURIComponent(value)}`, 'Path=/', 'HttpOnly', 'SameSite=Lax', `Max-Age=${maxAge}`]; if (isProduction()) attrs.push('Secure'); res.setHeader('Set-Cookie', attrs.join('; ')); }
export function clearCookie(res) { setCookie(res, '', 0); }
export function signSession() { const secret = process.env.ADMIN_SESSION_SECRET; if (!secret) throw new Error('session secret unavailable'); const payload = Buffer.from(JSON.stringify({ exp: Date.now() + 4 * 60 * 60 * 1000, n: cryptoRandom() })).toString('base64url'); return `${payload}.${createHmac('sha256', secret).update(payload).digest('base64url')}`; }
export function verifySession(token) { const secret = process.env.ADMIN_SESSION_SECRET; if (!secret || !token) return false; const [payload, signature] = token.split('.'); if (!payload || !signature) return false; const expected = createHmac('sha256', secret).update(payload).digest(); let actual; try { actual = Buffer.from(signature, 'base64url'); } catch { return false; } if (actual.length !== expected.length || !timingSafeEqual(actual, expected)) return false; try { return JSON.parse(Buffer.from(payload, 'base64url').toString()).exp > Date.now(); } catch { return false; } }
function cryptoRandom() { return `${Date.now()}-${Math.random().toString(36).slice(2)}`; }
