import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { decks } from '../dist/data/decks.js';
import { accountConfig } from './accounts.mjs';

const MIN = 6; const MAX = 40; const UUID = /^[0-9a-f-]{16,64}$/i;
const STATIC = new Map(decks.flatMap((deck) => [...(deck.questions || []), ...(deck.r18Questions || [])].map((card) => [card.id, { id: card.id, text: card.text, r18: Boolean(card.r18 || deck.adultOnly), kind: card.kind || 'question' }])));
const fail = (status, code) => Object.assign(new Error(code), { status, code });
const rawToken = () => randomBytes(24).toString('base64url');
const sha = (value) => createHash('sha256').update(value).digest('hex');
const keyFor = (secret) => createHash('sha256').update(`mingle venue qr v1:${secret}`).digest();
const text = (value, max) => typeof value === 'string' && value.trim() && Array.from(value.trim()).length <= max ? value.trim() : null;
function httpsUrl(value) { if (value == null || value === '') return null; if (typeof value !== 'string' || value.length > 240) return null; try { const parsed = new URL(value.trim()); return parsed.protocol === 'https:' ? parsed.toString() : null; } catch { return null; } }
function requestOrigin(req) { const host = String(req.headers?.host || '').toLowerCase(); if (!/^(mingle\.cards|www\.mingle\.cards|localhost(?::\d+)?|127\.0\.0\.1(?::\d+)?)$/.test(host)) return 'https://mingle.cards'; const proto = host.startsWith('localhost') || host.startsWith('127.') ? 'http' : 'https'; return `${proto}://${host}`; }
const object = (value) => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw fail(400, 'INVALID_REQUEST'); return value; };
function auth(req) { return /^Bearer\s+\S+$/i.test(req.headers?.authorization || '') ? req.headers.authorization : ''; }
async function rest(config, path, options = {}, fetchImpl = fetch) { const response = await fetchImpl(`${config.url}${path}`, { ...options, headers: { apikey: config.key, Authorization: options.headers?.Authorization || `Bearer ${config.key}`, Accept: 'application/json', ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...options.headers } }); let data = null; try { data = await response.json(); } catch {} if (!response.ok) throw fail(response.status === 401 ? 401 : response.status === 404 ? 404 : 502, response.status === 401 ? 'UNAUTHENTICATED' : response.status === 404 ? 'NOT_FOUND' : 'VENUE_UNAVAILABLE'); return data; }
function venue(v) { return { id: v.id, name: v.name, logoUrl: httpsUrl(v.logo_url), storeUrl: httpsUrl(v.store_url), endingUrl: httpsUrl(v.ending_url), welcomeText: v.welcome_text || '', adultEnabled: Boolean(v.adult_enabled), createdAt: v.created_at }; }
function setInfo(v) { return { id: v.id, venueId: v.venue_id, name: v.name, cardCount: v.card_count, adultOnly: Boolean(v.adult_only), active: v.active !== false, createdAt: v.created_at }; }
function tableInfo(v) { return { id: v.id, venueId: v.venue_id, label: v.label, active: v.active !== false, createdAt: v.created_at, revokedAt: v.revoked_at || null }; }
export function createVenueService({ env = process.env, fetchImpl = fetch } = {}) {
  const config = accountConfig(env); const serviceConfig = config?.serviceKey ? { ...config, key: config.serviceKey } : null;
  const qrKey = config?.serviceKey ? keyFor(config.serviceKey) : null;
  function encryptToken(value) { if (!qrKey) throw fail(503, 'VENUE_UNAVAILABLE'); const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', qrKey, iv); const encrypted = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${encrypted.toString('base64url')}`; }
  function decryptToken(value) { try { const [iv, tag, payload] = String(value || '').split('.').map((part) => Buffer.from(part, 'base64url')); const decipher = createDecipheriv('aes-256-gcm', qrKey, iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(payload), decipher.final()]).toString('utf8'); } catch { return null; } }
  async function requireUser(req) { if (!config) throw fail(503, 'VENUE_UNAVAILABLE'); const bearer = auth(req); if (!bearer) throw fail(401, 'UNAUTHENTICATED'); const user = await rest(config, '/auth/v1/user', { headers: { Authorization: bearer } }, fetchImpl); if (!user?.id) throw fail(401, 'UNAUTHENTICATED'); return { id: user.id, bearer }; }
  async function ownerVenue(req, id) { const owner = await requireUser(req); if (!UUID.test(id)) throw fail(400, 'INVALID_REQUEST'); const rows = await rest(config, `/rest/v1/venues?id=eq.${encodeURIComponent(id)}&owner_id=eq.${encodeURIComponent(owner.id)}&select=*`, { headers: { Authorization: owner.bearer } }, fetchImpl); if (!rows?.[0]) throw fail(404, 'NOT_FOUND'); return { owner, row: rows[0] }; }
  async function list(req) { const owner = await requireUser(req); const rows = await rest(config, `/rest/v1/venues?owner_id=eq.${encodeURIComponent(owner.id)}&select=*&order=created_at.asc,id.asc`, { headers: { Authorization: owner.bearer } }, fetchImpl) || []; const ids = rows.map((v) => v.id); const inIds = ids.length ? ids.join(',') : '00000000-0000-0000-0000-000000000000'; const sets = await rest(config, `/rest/v1/venue_sets?venue_id=in.(${inIds})&select=id,venue_id,name,card_count,adult_only,active,created_at&order=created_at.asc,id.asc`, { headers: { Authorization: owner.bearer } }, fetchImpl); const tables = await rest(config, `/rest/v1/venue_tables?venue_id=in.(${inIds})&select=id,venue_id,label,token_ciphertext,active,created_at,revoked_at&order=created_at.asc,id.asc`, { headers: { Authorization: owner.bearer } }, fetchImpl); return { venues: rows.map(venue), sets: sets.map(setInfo), tables: tables.map((row) => { const raw = row.active !== false ? decryptToken(row.token_ciphertext) : null; return { ...tableInfo(row), url: raw ? `${requestOrigin(req)}/venue.html?token=${encodeURIComponent(raw)}` : null }; }) }; }
  async function create(req) { const owner = await requireUser(req); const input = object(req.body); const name = text(input.name, 80); const logoUrl = input.logoUrl == null ? null : httpsUrl(input.logoUrl); const storeUrl = input.storeUrl == null ? null : httpsUrl(input.storeUrl); const endingUrl = input.endingUrl == null ? null : httpsUrl(input.endingUrl); if (!name || (input.logoUrl != null && !logoUrl) || (input.storeUrl != null && !storeUrl) || (input.endingUrl != null && !endingUrl) || (input.welcomeText !== undefined && (typeof input.welcomeText !== 'string' || input.welcomeText.length > 240)) || (input.adultEnabled !== undefined && typeof input.adultEnabled !== 'boolean')) throw fail(400, 'INVALID_REQUEST'); const rows = await rest(config, '/rest/v1/venues', { method: 'POST', body: JSON.stringify({ owner_id: owner.id, name, logo_url: logoUrl, store_url: storeUrl, ending_url: endingUrl, welcome_text: (input.welcomeText || '').trim(), adult_enabled: input.adultEnabled === true }), headers: { Authorization: owner.bearer, Prefer: 'return=representation' } }, fetchImpl); return { venue: venue(Array.isArray(rows) ? rows[0] : rows) }; }
  async function update(req, id) { const found = await ownerVenue(req, id); const input = object(req.body); const update = {}; for (const [key, column] of [['name','name'],['logoUrl','logo_url'],['storeUrl','store_url'],['endingUrl','ending_url']]) if (input[key] !== undefined) { update[column] = input[key] == null ? null : key === 'name' ? text(input[key], 80) : httpsUrl(input[key]); if (key !== 'name' && input[key] != null && !update[column]) throw fail(400, 'INVALID_REQUEST'); if (key === 'name' && !update[column]) throw fail(400, 'INVALID_REQUEST'); } if (input.welcomeText !== undefined) { if (typeof input.welcomeText !== 'string' || input.welcomeText.length > 240) throw fail(400, 'INVALID_REQUEST'); update.welcome_text = input.welcomeText.trim(); } if (input.adultEnabled !== undefined) { if (typeof input.adultEnabled !== 'boolean') throw fail(400, 'INVALID_REQUEST'); update.adult_enabled = input.adultEnabled; } if (!Object.keys(update).length) throw fail(400, 'INVALID_REQUEST'); const rows = await rest(config, `/rest/v1/venues?id=eq.${encodeURIComponent(id)}&owner_id=eq.${encodeURIComponent(found.owner.id)}`, { method: 'PATCH', body: JSON.stringify(update), headers: { Authorization: found.owner.bearer, Prefer: 'return=representation' } }, fetchImpl); if (!rows?.[0]) throw fail(404, 'NOT_FOUND'); return { venue: venue(rows[0]) }; }
  async function addSet(req, venueId) { const found = await ownerVenue(req, venueId); const input = object(req.body); const name = text(input.name, 80); if (!name || !['standard', 'my_set'].includes(input.sourceType) || typeof input.sourceId !== 'string') throw fail(400, 'INVALID_REQUEST'); let cards; if (input.sourceType === 'standard') { const deck = decks.find((d) => d.id === input.sourceId); if (!deck || (deck.adultOnly && !found.row.adult_enabled)) cards = []; else cards = [...(deck.questions || []), ...(deck.adultOnly ? (deck.r18Questions || []) : [])].slice(0, MAX).map((c) => ({ id: c.id, text: c.text, r18: Boolean(c.r18 || deck.adultOnly), kind: c.kind || 'question' })); } else { const sets = await rest(config, `/rest/v1/my_sets?id=eq.${encodeURIComponent(input.sourceId)}&user_id=eq.${encodeURIComponent(found.owner.id)}&select=id,card_ids`, { headers: { Authorization: found.owner.bearer } }, fetchImpl); if (!sets?.[0]) throw fail(404, 'NOT_FOUND'); const custom = await rest(config, `/rest/v1/custom_cards?user_id=eq.${encodeURIComponent(found.owner.id)}&select=id,text,r18`, { headers: { Authorization: found.owner.bearer } }, fetchImpl); const customMap = new Map((custom || []).map((c) => [`custom:${c.id}`, c])); const ids = sets[0].card_ids || []; if (ids.length < MIN || ids.length > MAX || new Set(ids).size !== ids.length) throw fail(400, 'SET_NOT_PLAYABLE'); cards = ids.map((id) => id.startsWith('custom:') ? (customMap.has(id) ? { id, text: customMap.get(id).text, r18: Boolean(customMap.get(id).r18), kind: 'question' } : null) : (STATIC.get(id) || null)); if (cards.some((c) => !c)) throw fail(400, 'SET_NOT_PLAYABLE'); } if (!cards || cards.length < MIN || cards.length > MAX) throw fail(400, 'SET_NOT_PLAYABLE'); if (cards.some((c) => c.r18) && !found.row.adult_enabled) throw fail(400, 'ADULT_VENUE_REQUIRED'); const rows = await rest(config, '/rest/v1/venue_sets', { method: 'POST', body: JSON.stringify({ venue_id: venueId, name, cards, card_count: cards.length, adult_only: cards.some((c) => c.r18) }), headers: { Authorization: found.owner.bearer, Prefer: 'return=representation' } }, fetchImpl); return { set: setInfo(Array.isArray(rows) ? rows[0] : rows) }; }
  async function updateSet(req, setId) { const owner = await requireUser(req); if (!UUID.test(setId)) throw fail(400, 'INVALID_REQUEST'); const rows = await rest(config, `/rest/v1/venue_sets?id=eq.${encodeURIComponent(setId)}&select=id,venue_id,active,adult_only,venues!inner(owner_id,adult_enabled)`, { headers: { Authorization: owner.bearer } }, fetchImpl); if (!rows?.[0] || rows[0].venues?.owner_id !== owner.id) throw fail(404, 'NOT_FOUND'); const input = object(req.body); if (typeof input.active !== 'boolean') throw fail(400, 'INVALID_REQUEST'); if (input.active && rows[0].adult_only && !rows[0].venues.adult_enabled) throw fail(400, 'ADULT_VENUE_REQUIRED'); await rest(config, `/rest/v1/venue_sets?id=eq.${encodeURIComponent(setId)}`, { method: 'PATCH', body: JSON.stringify({ active: input.active }), headers: { Authorization: owner.bearer } }, fetchImpl); return { active: input.active }; }
  async function issueTable(req, venueId) { const found = await ownerVenue(req, venueId); const input = object(req.body); const label = text(input.label, 60); if (!label) throw fail(400, 'INVALID_REQUEST'); const raw = rawToken(); const rows = await rest(config, '/rest/v1/venue_tables', { method: 'POST', body: JSON.stringify({ venue_id: venueId, label, token_hash: sha(raw), token_ciphertext: encryptToken(raw) }), headers: { Authorization: found.owner.bearer, Prefer: 'return=representation' } }, fetchImpl); const row = Array.isArray(rows) ? rows[0] : rows; const origin = requestOrigin(req); return { table: { ...tableInfo(row), url: `${origin}/venue.html?token=${encodeURIComponent(raw)}`, token: raw } }; }
  async function rotateTable(req, id) { const found = await requireUser(req); const rows = await rest(config, `/rest/v1/venue_tables?id=eq.${encodeURIComponent(id)}&select=id,venue_id,label`, { headers: { Authorization: found.bearer } }, fetchImpl); if (!rows?.[0]) throw fail(404, 'NOT_FOUND'); const owners = await rest(config, `/rest/v1/venues?id=eq.${encodeURIComponent(rows[0].venue_id)}&owner_id=eq.${encodeURIComponent(found.id)}&select=id`, { headers: { Authorization: found.bearer } }, fetchImpl); if (!owners?.[0]) throw fail(404, 'NOT_FOUND'); const raw = rawToken(); const updated = await rest(config, `/rest/v1/venue_tables?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify({ token_hash: sha(raw), token_ciphertext: encryptToken(raw), active: true, revoked_at: null }), headers: { Authorization: found.bearer, Prefer: 'return=representation' } }, fetchImpl); const origin = requestOrigin(req); return { table: { ...tableInfo(updated[0] || rows[0]), url: `${origin}/venue.html?token=${encodeURIComponent(raw)}`, token: raw } }; }
  async function revokeTable(req, id) { const found = await requireUser(req); const rows = await rest(config, `/rest/v1/venue_tables?id=eq.${encodeURIComponent(id)}&select=id,venue_id`, { headers: { Authorization: found.bearer } }, fetchImpl); if (!rows?.[0]) throw fail(404, 'NOT_FOUND'); const owners = await rest(config, `/rest/v1/venues?id=eq.${encodeURIComponent(rows[0].venue_id)}&owner_id=eq.${encodeURIComponent(found.id)}&select=id`, { headers: { Authorization: found.bearer } }, fetchImpl); if (!owners?.[0]) throw fail(404, 'NOT_FOUND'); await rest(config, `/rest/v1/venue_tables?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify({ active: false, revoked_at: new Date().toISOString() }), headers: { Authorization: found.bearer } }, fetchImpl); return { revoked: true }; }
  async function publicLookup(raw) { if (!serviceConfig || typeof raw !== 'string' || !/^[A-Za-z0-9_-]{32}$/.test(raw)) throw fail(404, 'NOT_FOUND'); const rows = await rest(serviceConfig, `/rest/v1/venue_tables?token_hash=eq.${encodeURIComponent(sha(raw))}&active=is.true&select=id,label,venue_id,venues(id,name,logo_url,store_url,ending_url,welcome_text,adult_enabled)&limit=1`, { headers: { Authorization: `Bearer ${serviceConfig.key}` } }, fetchImpl); const row = rows?.[0]; if (!row || !row.venues) throw fail(404, 'NOT_FOUND'); const sets = await rest(serviceConfig, `/rest/v1/venue_sets?venue_id=eq.${encodeURIComponent(row.venue_id)}&active=is.true&select=id,venue_id,name,card_count,adult_only,active&order=created_at.asc,id.asc`, { headers: { Authorization: `Bearer ${serviceConfig.key}` } }, fetchImpl); return { table: { id: row.id, label: row.label }, venue: row.venues, sets: (sets || []).filter((set) => !set.adult_only || row.venues.adult_enabled) }; }
  async function publicInfo(req, raw, start = false) { const found = await publicLookup(raw); if (!start) return { venue: venue(found.venue), table: found.table, sets: found.sets.map(setInfo) }; const input = object(req.body); const setId = typeof input.setId === 'string' ? input.setId : ''; const selected = found.sets.find((s) => s.id === setId); if (!selected) throw fail(404, 'NOT_FOUND'); if (!Array.isArray(input.participants) || input.participants.length < 2 || input.participants.length > 8 || input.participants.some((x) => typeof x !== 'string') || typeof input.adultConfirmed !== 'boolean') throw fail(400, 'INVALID_REQUEST'); if (selected.adult_only && (!found.venue.adult_enabled || input.adultConfirmed !== true)) throw fail(403, 'ADULT_CONSENT_REQUIRED'); const full = await rest(serviceConfig, `/rest/v1/venue_sets?id=eq.${encodeURIComponent(selected.id)}&venue_id=eq.${encodeURIComponent(found.venue.id)}&active=is.true&select=id,name,cards,card_count,adult_only`, { headers: { Authorization: `Bearer ${serviceConfig.key}` } }, fetchImpl); const snap = full?.[0]; if (!snap?.cards || snap.cards.length < MIN) throw fail(404, 'NOT_FOUND'); const snapshotAdult = Boolean(snap.adult_only) || snap.cards.some((card) => card && card.r18 === true); if (snapshotAdult && (!found.venue.adult_enabled || input.adultConfirmed !== true)) throw fail(403, 'ADULT_CONSENT_REQUIRED'); const session = rawToken(); await rest(serviceConfig, '/rest/v1/venue_usage_events', { method: 'POST', body: JSON.stringify({ venue_id: found.venue.id, venue_set_id: selected.id, table_id: found.table.id, session_hash: sha(session), event_type: 'started', round_index: 1 }), headers: { Authorization: `Bearer ${serviceConfig.key}`, Prefer: 'resolution=ignore-duplicates' } }, fetchImpl); return { venue: venue(found.venue), table: found.table, set: setInfo({ ...selected, adult_only: snapshotAdult }), participants: input.participants.map((x) => text(x, 40) || '参加者'), cards: snap.cards, session }; }
  async function analytics(req, raw) { if (!serviceConfig) throw fail(503, 'VENUE_UNAVAILABLE'); const input = object(req.body); const round = Number(input.roundIndex); if (input.eventType !== 'completed_round' || typeof input.session !== 'string' || !/^[A-Za-z0-9_-]{32}$/.test(input.session) || typeof input.setId !== 'string' || !Number.isInteger(round) || round < 1) throw fail(400, 'INVALID_REQUEST'); const found = await publicLookup(raw); const selected = found.sets.find((s) => s.id === input.setId); if (!selected || round > Math.floor(selected.card_count / 6)) throw fail(400, 'ROUND_NOT_COMPLETE'); const existing = await rest(serviceConfig, `/rest/v1/venue_usage_events?table_id=eq.${encodeURIComponent(found.table.id)}&venue_set_id=eq.${encodeURIComponent(input.setId)}&session_hash=eq.${encodeURIComponent(sha(input.session))}&event_type=eq.started&select=id&limit=1`, { headers: { Authorization: `Bearer ${serviceConfig.key}` } }, fetchImpl); if (!existing?.length) throw fail(403, 'SESSION_NOT_STARTED'); await rest(serviceConfig, '/rest/v1/venue_usage_events', { method: 'POST', body: JSON.stringify({ venue_id: found.venue.id, venue_set_id: input.setId, table_id: found.table.id, session_hash: sha(input.session), event_type: input.eventType, round_index: round }), headers: { Authorization: `Bearer ${serviceConfig.key}`, Prefer: 'resolution=ignore-duplicates' } }, fetchImpl); return { accepted: true }; }
  async function allUsage(venueId, authorization) { const all = []; for (let offset = 0;; offset += 1000) { const page = await rest(config, `/rest/v1/venue_usage_events?venue_id=eq.${encodeURIComponent(venueId)}&select=venue_set_id,event_type,created_at&order=created_at.asc,id.asc&limit=1000&offset=${offset}`, { headers: { Authorization: authorization } }, fetchImpl) || []; all.push(...page); if (page.length < 1000) return all; } }
  async function stats(req, venueId) { const found = await ownerVenue(req, venueId); const rows = await allUsage(venueId, found.owner.bearer); const totals = { starts: rows.filter((r) => r.event_type === 'started').length, completedRounds: rows.filter((r) => r.event_type === 'completed_round').length }; const popularThemes = Object.entries(rows.filter((r) => r.event_type === 'started').reduce((m, r) => (m[r.venue_set_id] = (m[r.venue_set_id] || 0) + 1, m), {})).sort((a,b) => b[1]-a[1]).map(([setId,count]) => ({ setId, count })); return { totals, popularThemes }; }
  return { list, create, update, addSet, updateSet, issueTable, rotateTable, revokeTable, publicInfo, analytics, stats, available: Boolean(config) };
}
